name: iac apply

on:
  workflow_run:
    workflows: ["tfsec scan"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Development Plan

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init + Plan
        run: |
          cd development
          terraform init
          mkdir -p ../tfplan-development
          terraform plan -out=../tfplan-development/plan.binary
          terraform show -no-color ../tfplan-development/plan.binary > ../tfplan-development/plan.txt

      - name: Upload development plan
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-development
          path: tfplan-development

