name: tfsec scan

on:
  push:

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
